package:
  name: python
  version: 1.1

source: 
  fn: python1.1.tar.gz  # [not osx]
  url: http://legacy.python.org/download/releases/src/python1.1.tar.gz  # [not osx]
  sha256: b7dcca096b521dfc12ecfc28612be9fc81ae0ce2fcd39182e38e40f0c7720e81
  patches:
    # Modules/fileobject.c defines a getline function which conflicts with the
    # one in stdio.h, rename the function in the file to _getline
    - fileobject_getline.patch  # [not osx]
    - setup.in_lcrypt.patch  # [not osx]

build:
  number: 0
  skip: True  # [win]
  # /lib/python uses a prefix to set the initial sys path, this needs to be
  # replace with the install prefix at installation
  detect_binary_files_with_prefix: True

test:
  commands:
    - python -c "import sys; sys.path.append('./')"
    - python -c "import sys; print sys.version"
    - python -c "import sys; print sys.path"
    # struct is a compiled module
    - python -c "import struct"
    # os is a python module, import will fail if sys.path is incorrect
    - python -c "import os"

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
